name: aiaf
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.6.15=h4c7d964_0
  - cairo=1.18.0=h32b962e_3
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.14=py310h9e98ed7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py310h38315fa_0
  - freetype=2.13.3=h57928b3_1
  - graphite2=1.3.14=he0c23c2_0
  - harfbuzz=9.0.0=h2bedf89_1
  - icu=75.1=he0c23c2_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=32_h641d27c_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=32_h5e41251_mkl
  - libclang13=20.1.7=default_h6e92b77_0
  - libdeflate=1.24=h76ddb4d_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_3
  - libglib=2.84.0=h7025463_0
  - libgomp=15.1.0=h1383e82_3
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=32_h1aa476e_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.49=h7a4582a_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.2=hf5d6505_0
  - libtiff=4.7.0=h05922d8_5
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h442d1da_0
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - matplotlib=3.10.3=py310h5588dad_0
  - matplotlib-base=3.10.3=py310h37e0a56_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2024.2.2=h66d3029_15
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.1=h725018a_0
  - pandas=2.3.0=py310hb4db72f_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h99c9b8b_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pixman=0.46.2=had0cd8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310ha8f682b_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.8.1=py310h60c6385_0
  - python=3.10.16=hfdde91d_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=7_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=307=py310h9e98ed7_3
  - pyzmq=27.0.0=py310h656833d_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.1=h2fedb45_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=78.1.1=py310haa95532_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py310h8f3aa81_2
  - tbb=2021.13.0=h62715c5_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.1=py310ha8f682b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py310ha8f682b_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_26
  - vs2015_runtime=14.44.35208=h38c0c73_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310haa95532_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.1
      - adversarial-robustness-toolbox==1.17.0
      - advertorch==0.2.3
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - alembic==1.16.4
      - annotated-types==0.7.0
      - ansicon==1.89.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autoattack==0.1
      - banal==1.0.6
      - beautifulsoup4==4.13.4
      - blessed==1.21.0
      - blinker==1.9.0
      - boto3==1.40.28
      - botocore==1.40.28
      - braceexpand==0.1.7
      - certifi==2025.6.15
      - chardet==4.0.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - cmake==4.0.3
      - coloredlogs==15.0.1
      - cython==3.1.2
      - dataset==1.6.2
      - deepface==0.0.95
      - dill==0.4.0
      - dlib==20.0.0
      - docker==7.1.0
      - easydict==1.13
      - face-recognition==1.3.0
      - face-recognition-models==0.3.0
      - facenet-pytorch==2.6.0
      - fastapi==0.116.1
      - filelock==3.13.1
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.2.10
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.3
      - grpcio==1.73.1
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.14.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==2.10
      - imageio==2.37.0
      - importlib-metadata==6.11.0
      - insightface==0.7.3
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jinxed==1.3.0
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==3.10.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.15.2
      - lpips==0.1.4
      - lz4==4.4.4
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mock==4.0.3
      - mpmath==1.3.0
      - mtcnn==1.0.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - namex==0.1.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cudnn-cu12==9.11.0.98
      - nvidia-ml-py==13.580.65
      - omegaconf==2.3.0
      - onnx==1.18.0
      - onnxruntime-gpu==1.23.2
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.16.0
      - packaging==24.2
      - pathos==0.3.4
      - pillow==10.2.0
      - pip==25.2
      - pox==0.3.6
      - ppft==1.7.7
      - prettytable==3.16.0
      - propcache==0.4.1
      - protobuf==5.29.5
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyreadline3==3.5.4
      - pysocks==1.7.1
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.10.23
      - requests==2.32.5
      - retina-face==0.0.17
      - rich==14.0.0
      - rpds-py==0.27.1
      - s3transfer==0.14.0
      - safetensors==0.5.3
      - sagemaker==2.251.1
      - sagemaker-core==1.0.59
      - schema==0.7.7
      - scikit-image==0.25.2
      - scikit-learn==1.1.3
      - scipy==1.15.3
      - sentry-sdk==2.35.0
      - simsimd==6.5.0
      - smdebug-rulesconfig==1.0.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==1.4.54
      - starlette==0.47.3
      - stringzilla==3.12.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - tblib==3.1.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tifffile==2025.5.10
      - timm==1.0.16
      - tokenizers==0.22.1
      - tomli==2.2.1
      - torch==2.2.0+cu121
      - torchattacks==3.5.1
      - torchaudio==2.2.0+cu121
      - torchmetrics==1.8.2
      - torchvision==0.17.0+cu121
      - transformers==4.57.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - urllib3==1.26.20
      - uvicorn==0.35.0
      - wandb==0.21.1
      - webdataset==0.2.100
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yacs==0.1.8
      - yarl==1.22.0
prefix: C:\Users\kamal\anaconda3\envs\aiaf
